import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Footer() {
  return (
    <footer className="footer bg-dark text-white fixed-bottom">
      <div className="container py-3">
        <p className="text-center mb-0">Examen Práctico</p>
      </div>
    </footer>
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={inter.className}>
        <div>
          <header>
            <nav className='navbar navbar-expand-md navbar-dark bg-dark' data-bs-theme="dark">
              <a href='/pacientes' className='navbar-brand'>Pacientes</a>
            </nav>
          </header>
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
